---
title: "《SPSS与统计实验》课程实验报告"
---

# 选题要求

运用统计方法分析现实问题。

# 数据要求

-   微观层面的截面数据

-   样本容量大于100

-   至少3个定量变量，至少3个定性变量，建议变量个数超过8个

-   不要使用其他教材中的例题或习题数据，不要使用虚拟数据

# 实验报告形式

**注意：论文的形式，不是PPT等演示文稿形式。**


## 封面

-   题目

-   小组成员信息（按学号顺序排列）

    -   班级 学号 成员1

    -   班级 学号 成员2

    -   班级 学号 成员3

## 1 前言

介绍研究背景、选题动机、研究目标。

## 2 数据概况

介绍数据来源、数据收集过程、解释变量的含义。

## 3 描述性统计分析：Chap 3 & 4

运用表格或图形呈现关键变量的分布特征、报告其描述性统计量。

## 4 参数估计: Chap 7

运用参数估计方法对总体参数（关键变量）进行推断。

## 5 假设检验：Chap 8

运用假设检验对总体参数（关键变量）进行推断。

## 6 独立性检验: Chap 9

运用独立性检验讨论两个定性变量之间的关系。

## 7 方差分析: Chap 10

运用方差分析讨论定性变量和定量变量之间的关系。

## 8 相关与回归分析: Chap 11

运用方差分析讨论定性变量和定量变量之间的关系。

## 9 结论和展望

总结研究结论, 本研究的不足, 值得进一步研究的问题

## 10 个人心得体会（每个小组成员独立撰写）

班级 学号 成员1

-   本人在完成实验报告中的具体工作

-   遇到过什么困难，如何解决该困难

-   课程建议

-   单个成员的心得体会字数不少于500字

# 实验报告提交要求

## 电子版

-   提交时限：第17周上课日的前一天的19:00

-   PDF版实验报告和数据文件提交到QQ群中的“实验报告及其数据文件”文件夹

-   PDF文件命名格式：“小组编号 组长名 组长班级 实验报告.pdf”

-   Excel或SPSS数据文件命名格式：“小组编号 组长名 组长班级 实验报告.xlsx/sav”

## 纸质版

-   双面或单面打印皆可，黑白打印即可，无需彩色打印，无需制作硬壳封面, 三颗订书针装订。

-   提交时限：第17周上课日




